/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { Helmet } from 'react-helmet';
import { Link } from 'react-router-dom';
import { styled } from '@mui/material/styles';
import Paragraph from 'src/components/Paragraph/Paragraph';
import Button1 from 'src/components/Button1/Button1';
import { Frame1038Props } from 'src/types';

const Frame10381: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  boxShadow: `0px 20px 20px rgba(0, 0, 0, 0.08), 0px 0px 2px rgba(0, 0, 0, 0.12)`,
  border: `1px solid rgba(222, 226, 230, 1)`,
  borderRadius: `8px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  height: 'auto',
  width: `750px`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `36px 40px`,
  boxSizing: `border-box`,
}));

const Frame1045: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  height: `362px`,
  margin: `0px`,
});

const Frame1039: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  flexGrow: `1`,
  height: `363px`,
  margin: `0px`,
});

const TermsAndAgreement: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(84, 89, 94, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `600`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
}));

const Frame1126: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  height: `330px`,
  margin: `16px 0px 0px 0px`,
  overflow: `hidden`,
});

const Paragraph1: any = styled(Paragraph)(({ theme }: any) => ({
  alignSelf: `stretch`,
  height: `330px`,
  margin: `0px`,
}));

const Frame167: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-end`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `36px 0px 0px 0px`,
});

const Button2: any = styled(Button1)(({ theme }: any) => ({
  width: `180px`,
  height: `44px`,
  margin: `0px`,
}));

const ExternalLink: any = styled('a')({
  width: `180px`,
  textDecoration: `none`,
});

const Button3: any = styled(Button1)(({ theme }: any) => ({
  width: `180px`,
  height: `44px`,
  margin: `0px 0px 0px 16px`,
}));

const InternalLink: any = styled(Link)({
  width: `180px`,
  textDecoration: `none`,
});

function Frame1038(props: Frame1038Props): JSX.Element {
  return (
    <Popover
      marginThreshold={0}
      anchorEl={undefined}
      anchorOrigin={{ vertical: 'top', horizontal: 'left' }}
      transformOrigin={{ vertical: 'top', horizontal: 'left' }}
      keepMounted
      transitionDuration={0}
      open={undefined}
      onClose={undefined}
    >
      <Frame10381 className={props.className}>
        <Helmet>
          <title>Frame 1038</title>
        </Helmet>
        <Frame1045>
          <Frame1039>
            <TermsAndAgreement>{`Terms and Agreement`}</TermsAndAgreement>
            <Frame1126>
              <Paragraph1 />
            </Frame1126>
          </Frame1039>
        </Frame1045>
        <Frame167>
          <ExternalLink href="https://swipeswi.pe">
            <Button2 />
          </ExternalLink>
          <InternalLink to="/home">
            <Button3 />
          </InternalLink>
        </Frame167>
      </Frame10381>
    </Popover>
  );
}

export default Frame1038;
