/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { Popover } from '@mui/material';
import VectorImage from 'src/assets/images/PLCard_Vector.png';
import Vector1Image from 'src/assets/images/PLCard_Vector_1.png';
import Vector2Image from 'src/assets/images/PLCard_Vector_2.png';
import Vector3Image from 'src/assets/images/PLCard_Vector_3.png';
import Vector4Image from 'src/assets/images/PLCard_Vector_4.png';
import Vector5Image from 'src/assets/images/PLCard_Vector_5.png';
import Vector6Image from 'src/assets/images/PLCard_Vector_6.png';
import Vector7Image from 'src/assets/images/PLCard_Vector_7.png';
import Vector8Image from 'src/assets/images/PLCard_Vector_8.png';
import Vector9Image from 'src/assets/images/PLCard_Vector_9.png';
import Vector10Image from 'src/assets/images/PLCard_Vector_10.png';
import Vector11Image from 'src/assets/images/PLCard_Vector_11.png';
import Vector12Image from 'src/assets/images/PLCard_Vector_12.png';
import Vector13Image from 'src/assets/images/PLCard_Vector_13.png';
import Vector14Image from 'src/assets/images/PLCard_Vector_14.png';
import Vector15Image from 'src/assets/images/PLCard_Vector_15.png';
import Vector16Image from 'src/assets/images/PLCard_Vector_16.png';
import Vector17Image from 'src/assets/images/PLCard_Vector_17.png';
import Vector18Image from 'src/assets/images/PLCard_Vector_18.png';
import Vector19Image from 'src/assets/images/PLCard_Vector_19.png';
import Vector20Image from 'src/assets/images/PLCard_Vector_20.png';
import Vector21Image from 'src/assets/images/PLCard_Vector_21.png';
import Vector22Image from 'src/assets/images/PLCard_Vector_22.png';
import Vector23Image from 'src/assets/images/PLCard_Vector_23.png';
import Vector24Image from 'src/assets/images/PLCard_Vector_24.png';
import { styled } from '@mui/material/styles';
import { PlCardProps } from 'src/types';

const PlCard1: any = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  borderRadius: `10px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `280px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Content: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  left: `40px`,
  top: `20px`,
});

const Title: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(43, 43, 43, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  height: `29px`,
  width: `370px`,
  margin: `0px`,
});

const Charts: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `150px`,
  width: `370px`,
  margin: `20px 0px 0px 0px`,
});

const SimpleBarChart: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `370px`,
  height: `150px`,
  left: `0px`,
  top: `0px`,
  overflow: `hidden`,
});

const PreviewInAnimaToSeeI: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `12px`,
  boxSizing: `border-box`,
  width: `370px`,
  height: `39px`,
  left: `0px`,
  top: `0px`,
  overflow: `hidden`,
});

const Frame: any = styled('div')({
  opacity: `0.4000000059604645`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  height: `28px`,
  margin: `0px`,
  overflow: `hidden`,
});

const PreviewInAnima: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(59, 59, 59, 1)`,
  fontStyle: `normal`,
  fontFamily: `Mulish`,
  fontWeight: `600`,
  fontSize: `10px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const Group: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `330.33px`,
  height: `120px`,
  left: `6px`,
  top: `30px`,
});

const Group1: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `330.33px`,
  height: `120px`,
  left: `0px`,
  top: `0px`,
});

const Group2: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `330.33px`,
  height: `120px`,
  left: `0px`,
  top: `0px`,
});

const Group3: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `22px`,
  height: `60px`,
  left: `0px`,
  top: `60px`,
});

const Vector: any = styled('img')({
  height: `60px`,
  width: `22px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Group4: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `22px`,
  height: `60px`,
  left: `62px`,
  top: `60px`,
});

const Vector1: any = styled('img')({
  height: `60px`,
  width: `22px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Group5: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `22px`,
  height: `100px`,
  left: `123px`,
  top: `20px`,
});

const Vector2: any = styled('img')({
  height: `100px`,
  width: `22px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Group6: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `22px`,
  height: `97.5px`,
  left: `185px`,
  top: `23px`,
});

const Vector3: any = styled('img')({
  height: `97.5px`,
  width: `22px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Group7: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `22px`,
  height: `120px`,
  left: `247px`,
  top: `0px`,
});

const Vector4: any = styled('img')({
  height: `120px`,
  width: `22px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Group8: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `22px`,
  height: `95px`,
  left: `308px`,
  top: `25px`,
});

const Vector5: any = styled('img')({
  height: `95px`,
  width: `22px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Group9: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `330.33px`,
  height: `100px`,
  left: `32px`,
  top: `50px`,
});

const Group10: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `330.33px`,
  height: `100px`,
  left: `0px`,
  top: `0px`,
});

const Group11: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `330.33px`,
  height: `100px`,
  left: `0px`,
  top: `0px`,
});

const Group12: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `22px`,
  height: `15px`,
  left: `0px`,
  top: `85px`,
});

const Vector6: any = styled('img')({
  height: `15px`,
  width: `22px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Group13: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `22px`,
  height: `25px`,
  left: `62px`,
  top: `75px`,
});

const Vector7: any = styled('img')({
  height: `25px`,
  width: `22px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Group14: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `22px`,
  height: `75px`,
  left: `123px`,
  top: `25px`,
});

const Vector8: any = styled('img')({
  height: `75px`,
  width: `22px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Group15: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `22px`,
  height: `52px`,
  left: `185px`,
  top: `48px`,
});

const Vector9: any = styled('img')({
  height: `52px`,
  width: `22px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Group16: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `22px`,
  height: `100px`,
  left: `247px`,
  top: `0px`,
});

const Vector10: any = styled('img')({
  height: `100px`,
  width: `22px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Group17: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `22px`,
  height: `25px`,
  left: `308px`,
  top: `75px`,
});

const Vector11: any = styled('img')({
  height: `25px`,
  width: `22px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const SimpleLineChart: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `370px`,
  height: `150px`,
  left: `0px`,
  top: `0px`,
  overflow: `hidden`,
});

const PreviewInAnimaToSeeI1: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `12px`,
  boxSizing: `border-box`,
  width: `370px`,
  height: `39px`,
  left: `0px`,
  top: `0px`,
  overflow: `hidden`,
});

const Frame1: any = styled('div')({
  opacity: `0.4000000059604645`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  height: `28px`,
  margin: `0px`,
  overflow: `hidden`,
});

const PreviewInAnima1: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(59, 59, 59, 1)`,
  fontStyle: `normal`,
  fontFamily: `Mulish`,
  fontWeight: `600`,
  fontSize: `10px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const Group18: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `370px`,
  height: `150px`,
  left: `0px`,
  top: `0px`,
});

const Group19: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `370px`,
  height: `150px`,
  left: `0px`,
  top: `0px`,
});

const Vector12: any = styled('img')({
  height: `0px`,
  width: `370px`,
  position: `absolute`,
  left: `0px`,
  top: `113px`,
});

const Vector13: any = styled('img')({
  height: `0px`,
  width: `370px`,
  position: `absolute`,
  left: `0px`,
  top: `75px`,
});

const Vector14: any = styled('img')({
  height: `0px`,
  width: `370px`,
  position: `absolute`,
  left: `0px`,
  top: `38px`,
});

const Vector15: any = styled('img')({
  height: `0px`,
  width: `370px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector16: any = styled('img')({
  height: `0px`,
  width: `370px`,
  position: `absolute`,
  left: `0px`,
  top: `150px`,
});

const Group20: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `370px`,
  height: `150px`,
  left: `0px`,
  top: `0px`,
});

const Vector17: any = styled('img')({
  height: `150px`,
  width: `0px`,
  position: `absolute`,
  left: `74px`,
  top: `0px`,
});

const Vector18: any = styled('img')({
  height: `150px`,
  width: `0px`,
  position: `absolute`,
  left: `148px`,
  top: `0px`,
});

const Vector19: any = styled('img')({
  height: `150px`,
  width: `0px`,
  position: `absolute`,
  left: `222px`,
  top: `0px`,
});

const Vector20: any = styled('img')({
  height: `150px`,
  width: `0px`,
  position: `absolute`,
  left: `296px`,
  top: `0px`,
});

const Vector21: any = styled('img')({
  height: `150px`,
  width: `0px`,
  position: `absolute`,
  left: `370px`,
  top: `0px`,
});

const Vector22: any = styled('img')({
  height: `150px`,
  width: `0px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Group21: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `370px`,
  height: `135px`,
  left: `0px`,
  top: `0px`,
});

const Vector23: any = styled('img')({
  height: `135px`,
  width: `370px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Group22: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `370px`,
  height: `60.25px`,
  left: `0px`,
  top: `55px`,
});

const Vector24: any = styled('img')({
  height: `60.25px`,
  width: `370px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Comment: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(43, 43, 43, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `20px`,
  textTransform: `none`,
  height: `21px`,
  width: `370px`,
  margin: `20px 0px 0px 0px`,
});

function PlCard(props: PlCardProps): JSX.Element {
  return (
    <PlCard1 className={props.className}>
      <Content>
        <Title>{`Profit & Loss`}</Title>
        <Charts>
          {false && (
            <SimpleBarChart>
              <PreviewInAnimaToSeeI>
                <Frame>
                  <PreviewInAnima>{`Preview in Anima`}</PreviewInAnima>
                </Frame>
              </PreviewInAnimaToSeeI>
              <Group>
                <Group1>
                  <Group2>
                    <Group3>
                      <Vector src={VectorImage} loading="lazy" alt={'Vector'} />
                    </Group3>
                    <Group4>
                      <Vector1
                        src={Vector1Image}
                        loading="lazy"
                        alt={'Vector'}
                      />
                    </Group4>
                    <Group5>
                      <Vector2
                        src={Vector2Image}
                        loading="lazy"
                        alt={'Vector'}
                      />
                    </Group5>
                    <Group6>
                      <Vector3
                        src={Vector3Image}
                        loading="lazy"
                        alt={'Vector'}
                      />
                    </Group6>
                    <Group7>
                      <Vector4
                        src={Vector4Image}
                        loading="lazy"
                        alt={'Vector'}
                      />
                    </Group7>
                    <Group8>
                      <Vector5
                        src={Vector5Image}
                        loading="lazy"
                        alt={'Vector'}
                      />
                    </Group8>
                  </Group2>
                </Group1>
              </Group>
              <Group9>
                <Group10>
                  <Group11>
                    <Group12>
                      <Vector6
                        src={Vector6Image}
                        loading="lazy"
                        alt={'Vector'}
                      />
                    </Group12>
                    <Group13>
                      <Vector7
                        src={Vector7Image}
                        loading="lazy"
                        alt={'Vector'}
                      />
                    </Group13>
                    <Group14>
                      <Vector8
                        src={Vector8Image}
                        loading="lazy"
                        alt={'Vector'}
                      />
                    </Group14>
                    <Group15>
                      <Vector9
                        src={Vector9Image}
                        loading="lazy"
                        alt={'Vector'}
                      />
                    </Group15>
                    <Group16>
                      <Vector10
                        src={Vector10Image}
                        loading="lazy"
                        alt={'Vector'}
                      />
                    </Group16>
                    <Group17>
                      <Vector11
                        src={Vector11Image}
                        loading="lazy"
                        alt={'Vector'}
                      />
                    </Group17>
                  </Group11>
                </Group10>
              </Group9>
            </SimpleBarChart>
          )}
          <SimpleLineChart>
            <PreviewInAnimaToSeeI1>
              <Frame1>
                <PreviewInAnima1>{`Preview in Anima`}</PreviewInAnima1>
              </Frame1>
            </PreviewInAnimaToSeeI1>
            <Group18>
              <Group19>
                <Vector12 src={Vector12Image} loading="lazy" alt={'Vector'} />
                <Vector13 src={Vector13Image} loading="lazy" alt={'Vector'} />
                <Vector14 src={Vector14Image} loading="lazy" alt={'Vector'} />
                <Vector15 src={Vector15Image} loading="lazy" alt={'Vector'} />
                <Vector16 src={Vector16Image} loading="lazy" alt={'Vector'} />
              </Group19>
              <Group20>
                <Vector17 src={Vector17Image} loading="lazy" alt={'Vector'} />
                <Vector18 src={Vector18Image} loading="lazy" alt={'Vector'} />
                <Vector19 src={Vector19Image} loading="lazy" alt={'Vector'} />
                <Vector20 src={Vector20Image} loading="lazy" alt={'Vector'} />
                <Vector21 src={Vector21Image} loading="lazy" alt={'Vector'} />
                <Vector22 src={Vector22Image} loading="lazy" alt={'Vector'} />
              </Group20>
            </Group18>
            <Group21>
              <Popover
                marginThreshold={0}
                anchorEl={undefined}
                anchorOrigin={{ vertical: 'top', horizontal: 'left' }}
                transformOrigin={{ vertical: 'top', horizontal: 'left' }}
                keepMounted
                transitionDuration={0}
                open={undefined}
                onClose={undefined}
              >
                <Vector23 src={Vector23Image} loading="lazy" alt={'Vector'} />
              </Popover>
            </Group21>
            <Group22>
              <Vector24 src={Vector24Image} loading="lazy" alt={'Vector'} />
            </Group22>
          </SimpleLineChart>
        </Charts>
        <Comment>{`Runway: Infinite`}</Comment>
      </Content>
    </PlCard1>
  );
}

export default PlCard;
